version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: yearly
    assignees:
      - Lruihao
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: yearly
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    assignees:
      - Lruihao
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
