name: Hugo FixIt Component List Workflow
description: Generate a list of all hugo-fixit theme components.
author: Lruihao

branding:
  icon: list
  color: blue

inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
